const fileList = [
  "./flows/active-or-pause-campaign.js",
  "./flows/export-campaign-file.js",
  "./flows/open-campaign-analytics.js",
  "./flows/update-campaign-name.js",
  "./flows/add-new-campaign.js",
  "./flows/forgot-password-request.js",
  "./flows/open-campaign-leads.js",
  "./flows/update-users-email.js",
  "./flows/add-new-member-in-workspace.js",
  "./flows/get-shareable-campaign-link.js",
  "./flows/open-campaign-options.js",
  "./flows/update-users-name.js",
  "./flows/connect-imap-or-smtp-email-account.js",
  "./flows/index.js",
  "./flows/open-campaign-schedule.js",
  "./flows/update-users-password.js",
  "./flows/delete-campaign.js",
  "./flows/login.js",
  "./flows/open-campaign-sequences.js",
  "./flows/update-workspace-name.js",
  "./flows/download-campaign-analytics.js",
  "./flows/logout.js",
  "./flows/open-email-setting.js",
  "./flows/duplicate-campaign.js",
  "./flows/navigate-to-side-menu.js",
  "./flows/sign-up.js",
  "./flows/enable-or-disable-email-warmup.js",
  "./flows/open-billings-page.js",
  "./flows/start-product-tour.js",
];

let flowMappings = {
  login: {
    func: login,
    number_of_args: "2",
    description: "Function to log in to the system.",
    args_ask_message:
      "Please share your email and password in the following format:\n\njohn@example.com,kahnak@ak#",
    url: "https://app.instantly.ai/auth/login",
  },
  logout: {
    func: logout,
    number_of_args: "0",
    description: "Function to log out of the system.",
    args_ask_message: "Do you want to log out? Enter Yes or No.",
    url: "https://app.instantly.ai/app/accounts",
  },
  addNewCampaign: {
    func: addNewCampaign,
    number_of_args: "1",
    description: "Function to add or create a new campaign.",
    args_ask_message: "Please enter a campaign name",
    url: "https://app.instantly.ai/app/campaigns",
  },
  deleteCampaign: {
    func: deleteCampaign,
    number_of_args: "1",
    description: "Function to delete a campaign.",
    args_ask_message: "Please enter a campaign id",
    url: "https://app.instantly.ai/app/campaigns",
  },
  downloadCampaignAnalytics: {
    func: downloadCampaignAnalytics,
    number_of_args: "1",
    description: "Function to download campaign analytics.",
    args_ask_message: "Please enter a campaign name",
    url: "https://app.instantly.ai/app/campaigns",
  },
  enableOrDisableEmailWarmup: {
    func: enableOrDisableEmailWarmup,
    number_of_args: "1",
    description: "Function to enable or disable email warm-up.",
    args_ask_message: "Please enter an email",
    url: "https://app.instantly.ai/app/accounts",
  },
  exportCampaignFile: {
    func: exportCampaignFile,
    number_of_args: "1",
    description: "Function to export a campaign file.",
    args_ask_message: "Please enter a campaign name",
    url: "https://app.instantly.ai/app/campaigns",
  },
  forgotPasswordRequest: {
    func: forgotPasswordRequest,
    number_of_args: "1",
    description: "Function to request a new password.",
    args_ask_message: "Please enter an email",
    url: "https://app.instantly.ai/auth/login",
  },
  getShareableCampaignLink: {
    func: getShareableCampaignLink,
    number_of_args: "1",
    description: "Function to get a shareable campaign link.",
    args_ask_message: "Please enter a campaign name",
    url: "https://app.instantly.ai/app/campaigns",
  },
  openBillingsPage: {
    func: openBillingsPage,
    number_of_args: "0",
    description: "Function to open the billing page.",
    args_ask_message: "Do you want to open the billing page? Enter Yes or No.",
    url: "https://app.instantly.ai/app/accounts",
  },
  openEmailSetting: {
    func: openEmailSetting,
    number_of_args: "1",
    description: "Function to open email settings.",
    args_ask_message: "Please enter an email",
    url: "https://app.instantly.ai/app/accounts",
  },
  startProductTour: {
    func: startProductTour,
    number_of_args: "0",
    description: "Function to start a product tour.",
    args_ask_message: "Do you want to start the product tour? Enter Yes or No.",
    url: "https://app.instantly.ai/app/accounts",
  },
  updateCampaignName: {
    func: updateCampaignName,
    number_of_args: "1",
    description: "Function to update a campaign name.",
    args_ask_message: "Please enter a campaign name",
    url: "https://app.instantly.ai/app/campaigns",
  },
  updateUsersEmail: {
    func: updateUsersEmail,
    number_of_args: "1",
    description: "Function to update the user's email.",
    args_ask_message: "Please enter an email",
    url: "https://app.instantly.ai/app/accounts",
  },
  updateUsersName: {
    func: updateUsersName,
    number_of_args: "2",
    description: "Function to update the user's name.",
    args_ask_message:
      "Please share your first name and last name in the following format:\n\njohn,Doe",
    url: "https://app.instantly.ai/app/accounts",
  },
  updateCurrentWorkspaceName: {
    func: updateCurrentWorkspaceName,
    number_of_args: "1",
    description: "Function to update the current workspace name.",
    args_ask_message: "Please enter a workspace name",
    url: "https://app.instantly.ai/app/accounts",
  },
  addNewMemberInWorkspace: {
    func: addNewMemberInWorkspace,
    number_of_args: "1",
    description: "Function to add or create a new member in the workspace.",
    args_ask_message: "Please enter an email for the new member",
    url: "https://app.instantly.ai/app/accounts",
  },
};

console.log("!!FLOW MAPPING LOADED!!");
